local root = (arg[0]:match("^(.*[/\\])") or "./") .. "../"
package.path = root .. "Scripts/?.lua;" .. package.path
local Policy = require("reservation_policy")

local policy = Policy.new()
assert(not policy:toggle(1, nil))
assert(policy:toggle(1, "wood"))
assert(policy:allows(1, "wood"))
assert(not policy:allows(1, "stone"))
assert(not policy:allows(1, nil))
assert(policy:allows(2, "stone"))
assert(policy:firstAllowedSlot({ 1, 2, 3 }, "stone", function() return true end) == 2)
assert(policy:firstAllowedSlot({ 1, 2 }, "stone", function(slot) return slot == 1 end) == nil)
assert(policy:firstAllowedSlot({ 1, 2 }, "wood", function(slot) return slot == 1 end) == 1)
assert(not policy:allowsSwap(1, "wood", 2, "stone"))
assert(policy:allowsSwap(1, "wood", 2, "wood"))
assert(not policy:toggle(1, nil))
assert(policy:allows(1, "stone"))
assert(policy:toggle(3, "potion"))
assert(not policy:allows(3, "wood"))
print("Reservation policy checks passed")
